In [8]:
import pandas as pd
df = pd.read_csv("../data/annonces-ventes-68.csv",delimiter=';',header=0,encoding="iso-8859-1")
print (df.shape)
display(df.head(10))

(27737, 59)

,idannonce,type_annonceur,typedebien,typedetransaction,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,...,UU2010,REG,DEP,loyer_m2_median_n6,nb_log_n6,taux_rendement_n6,loyer_m2_median_n7,nb_log_n7,taux_rendement_n7,prix_m2_vente
0,hektor-robischung-2862,pr,a,v,0.0,64.0,NaN,3.0,128400.0,NaN,...,68113.0,44.0,68.0,NaN,NaN,NaN,NaN,NaN,NaN,2006.25
1,apimo-82452515,pr,m,v,0.0,85.0,4950.0,4.0,189000.0,NaN,...,68000.0,44.0,68.0,NaN,NaN,NaN,NaN,NaN,NaN,2223.53
2,immo-facile-52471952,pr,m,v,0.0,187.0,3182.0,9.0,282900.0,NaN,...,68000.0,44.0,68.0,NaN,NaN,NaN,NaN,NaN,NaN,1512.83
3,immo-facile-52477215,pr,a,v,0.0,76.0,NaN,4.0,79000.0,NaN,...,68000.0,44.0,68.0,7.93,3.0,0.092,7.93,3.0,0.092,1039.47
4,ag681088-383601401,pr,m,v,0.0,90.0,3071.0,5.0,317000.0,NaN,...,68000.0,44.0,68.0,9.77,2.0,0.033,9.77,2.0,0.033,3522.22
5,ag681104-381823822,pr,m,v,0.0,90.0,872.0,4.0,170000.0,NaN,...,68000.0,44.0,68.0,9.20,1.0,0.058,9.20,1.0,0.058,1888.89
6,hektor-robischung-2873,pr,m,v,0.0,82.0,872.0,4.0,201000.0,NaN,...,68000.0,44.0,68.0,9.20,1.0,0.045,9.20,1.0,0.045,2451.22
7,ag681158-383546936,pr,m,v,0.0,82.0,11140.0,4.0,295000.0,NaN,...,68000.0,44.0,68.0,NaN,NaN,NaN,NaN,NaN,NaN,3597.56
8,ag751938-380728492,pr,a,v,5.0,82.0,NaN,4.0,160000.0,NaN,...,68701.0,44.0,68.0,9.56,12.0,0.059,9.22,388.0,0.057,1951.22
9,entities-1042950-3869684,pr,m,v,0.0,134.0,3797.0,4.0,413500.0,NaN,...,68302.0,44.0,68.0,NaN,NaN,NaN,NaN,NaN,NaN,3085.82