In [ ]:
import pandas as pd
df = pd.read_csv("../data/annonces-ventes-69.csv",delimiter=';',header=0,encoding="iso-8859-1",low_memory=False)
print (df.shape)
display(df.head(20))
df_m = df [df.typedebien == "m"]
print (df_m.shape)
print (df_m.info())
df_a = df [df.typedebien == "a"]
print (df_a.shape)
print (df_a.info())

(133369, 59)

,idannonce,type_annonceur,typedebien,typedetransaction,etage,surface,surface_terrain,nb_pieces,prix_bien,prix_maison,...,UU2010,REG,DEP,loyer_m2_median_n6,nb_log_n6,taux_rendement_n6,loyer_m2_median_n7,nb_log_n7,taux_rendement_n7,prix_m2_vente
0,entities-1039632-3305176,pr,m,v,0,50,233.0,3,279000,NaN,...,758,84,69,11.20,4.0,0.024,11.20,4.0,0.024,5580.00
1,hektor-actueltransactions-3769,pr,m,v,0,170,1222.0,6,450000,NaN,...,758,84,69,11.85,3.0,0.054,11.85,3.0,0.054,2647.06
2,hektor-avenirinvestissement-5792,pr,m,v,0,176,1000.0,5,695000,NaN,...,758,84,69,12.96,6.0,0.039,12.96,6.0,0.039,3948.86
3,ag011063-457293005,pr,m,v,0,210,450.0,6,695000,NaN,...,758,84,69,11.85,3.0,0.043,11.85,3.0,0.043,3309.52
4,netty-lannexeimmo2-house-1323,pr,m,v,0,142,643.0,6,769000,NaN,...,758,84,69,11.85,3.0,0.026,11.85,3.0,0.026,5415.49
5,iad-france-1751017,pr,m,v,0,274,925.0,8,950000,NaN,...,758,84,69,NaN,NaN,NaN,NaN,NaN,NaN,3467.15
6,hektor-1_flandin-2987,pr,a,v,1,85,NaN,4,347000,NaN,...,758,84,69,12.33,23.0,0.036,12.33,23.0,0.036,4082.35
7,entities-1037644-4587187,pr,m,v,0,94,370.0,4,415200,NaN,...,758,84,69,12.73,3.0,0.035,12.73,3.0,0.035,4417.02
8,entities-1037644-4587189,pr,m,v,0,101,370.0,5,410000,NaN,...,758,84,69,12.76,15.0,0.038,12.76,15.0,0.038,4059.41
9,immo-facile-47259141,pr,a,v,1,45,NaN,2,168000,NaN,...,758,84,69,16.42,15.0,0.053,16.42,15.0,0.053,3733.33
10,ag440414-457592894,pr,m,v,0,115,400.0,5,499000,NaN,...,758,84,69,12.76,15.0,0.035,12.76,15.0,0.035,4339.13
11,century-21-202_2117_59204,pr,m,v,0,172,2468.0,6,599000,NaN,...,758,84,69,11.58,5.0,0.040,11.58,5.0,0.040,3482.56
12,ag340369-456814790,pr,m,v,0,215,1509.0,7,735000,NaN,...,758,84,69,13.49,1.0,0.047,13.49,1.0,0.047,3418.60
13,hektor-1_flandin-3580,pr,m,v,0,173,1000.0,5,620000,NaN,...,758,84,69,12.76,15.0,0.043,12.76,15.0,0.043,3583.82
14,rodacom-5555636,pr,m,v,0,70,100.0,4,228000,NaN,...,69202,84,69,15.36,2.0,0.057,15.36,2.0,0.057,3257.14
15,rodacom-5552586,pr,m,vp,0,125,250.0,5,621000,NaN,...,69202,84,69,14.49,11.0,0.035,14.49,11.0,0.035,4968.00
16,century-21-202_772_22211,pr,a,v,1,110,NaN,5,249000,NaN,...,69202,84,69,10.96,2.0,0.058,10.96,2.0,0.058,2263.64
17,hektor-accorimm69100-3910,pr,m,v,0,93,260.0,4,358000,NaN,...,758,84,69,11.88,8.0,0.037,13.13,13.0,0.041,3849.46
18,entities-1037644-4587125,pr,m,v,0,94,425.0,4,381000,NaN,...,758,84,69,11.88,8.0,0.035,13.13,13.0,0.039,4053.19
19,laforet-immo-facile-22553614,pr,m,v,0,85,159.0,4,328000,NaN,...,758,84,69,11.88,8.0,0.037,13.13,13.0,0.041,3858.82

(38739, 59)
(89190, 59)
<class 'pandas.core.frame.DataFrame'>
Index: 89190 entries, 6 to 133368
Data columns (total 59 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   idannonce                89190 non-null  object
 1   type_annonceur           89190 non-null  object
 2   typedebien               89190 non-null  object
 3   typedetransaction        89190 non-null  object
 4   etage                    89190 non-null  int64
 5   surface                  89190 non-null  int64
 6   surface_terrain          3219 non-null   float64
 7   nb_pieces                89190 non-null  int64
 8   prix_bien                89190 non-null  int64
 9   prix_maison              0 non-null      float64
 10  prix_terrain             0 non-null      float64
 11  mensualiteFinance        89190 non-null  int64
 12  balcon                   89190 non-null  int64
 13  eau                      89190 non-null  int64
 14  bain                     89190 non-null  int64
 15  dpeL                     89190 non-null  object
 16  dpeC                     66735 non-null  float64
 17  mapCoordonneesLatitude   89190 non-null  float64
 18  mapCoordonneesLongitude  89190 non-null  float64
 19  annonce_exclusive        89190 non-null  object
 20  nb_etages                61027 non-null  float64
 21  parking                  352 non-null    object
 22  places_parking           28734 non-null  float64
 23  cave                     38954 non-null  object
 24  exposition               89190 non-null  object
 25  ges_class                73391 non-null  object
 26  annee_construction       34144 non-null  float64
 27  nb_toilettes             48360 non-null  float64
 28  nb_terraces              15798 non-null  float64
 29  videophone               984 non-null    object
 30  porte_digicode           20431 non-null  object
 31  surface_balcon           6179 non-null   float64
 32  ascenseur                64394 non-null  object
 33  nb_logements_copro       56446 non-null  float64
 34  charges_copro            49890 non-null  float64
 35  chauffage_energie        45879 non-null  object
 36  chauffage_systeme        26530 non-null  object
 37  chauffage_mode           52924 non-null  object
 38  categorie_annonceur      89190 non-null  object
 39  logement_neuf            87371 non-null  object
 40  duree_int                86586 non-null  float64
 41  typedebien_lite          89190 non-null  object
 42  date                     89190 non-null  object
 43  INSEE_COM                89190 non-null  int64
 44  IRIS                     89190 non-null  int64
 45  CODE_IRIS                89190 non-null  int64
 46  TYP_IRIS_x               89190 non-null  object
 47  TYP_IRIS_y               89190 non-null  object
 48  GRD_QUART                89190 non-null  int64
 49  UU2010                   89190 non-null  int64
 50  REG                      89190 non-null  int64
 51  DEP                      89190 non-null  int64
 52  loyer_m2_median_n6       86224 non-null  float64
 53  nb_log_n6                86224 non-null  float64
 54  taux_rendement_n6        86224 non-null  float64
 55  loyer_m2_median_n7       88426 non-null  float64
 56  nb_log_n7                88426 non-null  float64
 57  taux_rendement_n7        88426 non-null  float64
 58  prix_m2_vente            89190 non-null  float64
dtypes: float64(22), int64(15), object(22)
memory usage: 40.8+ MB
None